spring:
  application:
    name: bff #nombre con que mi bff se comunica con eruka
  config:
    import: optional:configserver:http://localhost:8888 #opcional por ahora el config server

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://cognito-idp.${cognito.region}.amazonaws.com/${cognito.user-pool-id}/.well-known/jwks.json
          issuer-uri: https://cognito-idp.${cognito.region}.amazonaws.com/${cognito.user-pool-id}
server:
  port: 8081 #puerto del bff

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #url del eureka

servicios: #configuración de los servicios
  rutas:
    mascotas: ms-mascotas #ruta/mascotas ->nombre en eureka
    alertas: ms-alertas #ruta/alertas ->nombre en eureka
    usuarios: ms-usuarios #ruta/usuarios ->nombre en eureka


bff:
  retry-after: 5 #tiempo de espera para reintentar la solicitud

cognito:
  region: us-east-1 #región de cognito
  user-pool-id: ${COGNITO_USER_POOL_ID} #id del user pool de cognito
  client-id: ${COGNITO_CLIENT_ID} #id del cliente de cognito

